[package]
description = "rustbolt swc minifier plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_swc_js_minimizer"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cow-utils = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
rustbolt_core = { workspace = true }
rustbolt_error = { workspace = true }
rustbolt_hash = { workspace = true }
rustbolt_hook = { workspace = true }
rustbolt_plugin_javascript = { workspace = true }
rustbolt_util = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
swc_config = { workspace = true }
swc_core = { workspace = true, features = [
  "__parser",
  "__utils",
  "common_sourcemap",
  "ecma_preset_env",
  "ecma_transforms_optimization",
  "ecma_transforms_module",
  "ecma_transforms_compat",
  "ecma_transforms_typescript",
  "ecma_quote",
] }
swc_ecma_minifier = { workspace = true, features = ["concurrent"] }
swc_parallel = { workspace = true, default-features = false }
tracing = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "swc_parallel"]
