packages:
  - "packages/*"
  - "scripts"
  - "website"
  - "tests/e2e/fixtures/**"
  - "packages/create-rustbolt/**"
  - "npm/*"
  - "crates/node_binding"
  - "examples/**"
  - "!examples/three"
  - "tests/e2e"
  - "tests/webpack-examples"
  - "tests/webpack-test"
  - "tests/webpack-cli-test"
  - "tests/bench"
  # this following is used to test resolve in monorepo
  - "packages/rustbolt-test-tools/tests/normalCases/resolve/pnpm-workspace/packages/*"
