[package]
description = "rustbolt javascript plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_javascript"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"
[dependencies]
anymap = { workspace = true }
async-trait = { workspace = true }
bitflags = { workspace = true }
cow-utils = { workspace = true }
dashmap = { workspace = true }
either = { workspace = true }
fast-glob = "0.4.4"
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
linked_hash_set = { workspace = true }
num-bigint = { version = "0.4.6" }
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
ropey = { workspace = true }
rustbolt_ast = { workspace = true }
rustbolt_cacheable = { workspace = true }
rustbolt_collections = { workspace = true }
rustbolt_core = { workspace = true }
rustbolt_error = { workspace = true }
rustbolt_futures = { workspace = true }
rustbolt_hash = { workspace = true }
rustbolt_hook = { workspace = true }
rustbolt_ids = { workspace = true }
rustbolt_paths = { workspace = true }
rustbolt_regex = { workspace = true }
rustbolt_util = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
sugar_path = { workspace = true }
swc_core = { workspace = true, features = [
  "__parser",
  "__utils",
  "common_sourcemap",
  "ecma_preset_env",
  "ecma_transforms_optimization",
  "ecma_transforms_module",
  "ecma_transforms_compat",
  "ecma_transforms_typescript",
  "base",
  "ecma_quote",
] }
swc_node_comments = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
stacker = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
