[package]
description = "rustbolt hmr plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_hmr"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"

[dependencies]
rustbolt_cacheable         = { workspace = true }
rustbolt_collections       = { workspace = true }
rustbolt_core              = { workspace = true }
rustbolt_error             = { workspace = true }
rustbolt_hash              = { workspace = true }
rustbolt_hook              = { workspace = true }
rustbolt_plugin_css        = { workspace = true }
rustbolt_plugin_javascript = { workspace = true }
rustbolt_util              = { workspace = true }

async-trait = { workspace = true }
cow-utils   = { workspace = true }
rustc-hash  = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "rustbolt_cacheable", "rustbolt_hash", "tokio"]
