[package]
description = "rustbolt wasm plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_wasm"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait        = { workspace = true }
cow-utils          = { workspace = true }
dashmap            = { workspace = true }
indexmap           = { workspace = true }
rayon              = { workspace = true }
rustbolt_cacheable   = { workspace = true }
rustbolt_collections = { workspace = true }
rustbolt_core        = { workspace = true }
rustbolt_error       = { workspace = true }
rustbolt_hash        = { workspace = true }
rustbolt_hook        = { workspace = true }
rustbolt_util        = { workspace = true }
serde_json         = { workspace = true }
swc_core           = { workspace = true, features = ["__ecma"] }
tokio              = { workspace = true }
tracing            = { workspace = true }
wasmparser         = "0.222.0"

[package.metadata.cargo-shear]
ignored = ["tracing", "rustbolt_hash", "tokio"]
