[package]
description = "rustbolt runtime plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_runtime"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait              = { workspace = true }
cow-utils                = { workspace = true }
dashmap                  = { workspace = true }
derive_more              = { workspace = true, features = ["debug"] }
futures                  = { workspace = true }
indexmap                 = { workspace = true }
itertools                = { workspace = true }
rustbolt_cacheable         = { workspace = true }
rustbolt_collections       = { workspace = true }
rustbolt_core              = { workspace = true }
rustbolt_error             = { workspace = true }
rustbolt_hash              = { workspace = true }
rustbolt_hook              = { workspace = true }
rustbolt_plugin_javascript = { workspace = true }
rustbolt_util              = { workspace = true }
tokio                    = { workspace = true }

rustc-hash = { workspace = true }
serde_json = { workspace = true }
tracing    = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "tokio"]
