[package]
description = "rustbolt sensitive module plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_warn_sensitive_module"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"

[dependencies]
cow-utils          = { workspace = true }
rustbolt_collections = { workspace = true }
rustbolt_core        = { workspace = true }
rustbolt_error       = { workspace = true }
rustbolt_hook        = { workspace = true }
rustc-hash         = { workspace = true }
tracing            = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
