[package]
description             = "rustbolt lazy compilation plugin"
documentation.workspace = true
edition                 = "2021"
homepage.workspace      = true
license                 = "MIT"
name                    = "rustbolt_plugin_lazy_compilation"
repository.workspace    = true
version                 = "0.2.0"

[dependencies]
async-trait = { workspace = true }
rustc-hash  = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }

rustbolt_cacheable         = { workspace = true }
rustbolt_collections       = { workspace = true }
rustbolt_core              = { workspace = true }
rustbolt_error             = { workspace = true }
rustbolt_hash              = { workspace = true }
rustbolt_hook              = { workspace = true }
rustbolt_plugin_javascript = { workspace = true }
rustbolt_regex             = { workspace = true }
rustbolt_util              = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
