[package]
description = "rustbolt devtool plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_devtool"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait              = { workspace = true }
cow-utils                = { workspace = true }
dashmap                  = { workspace = true }
derive_more              = { workspace = true, features = ["debug"] }
futures                  = { workspace = true }
itertools                = { workspace = true }
rayon                    = { workspace = true }
regex                    = { workspace = true }
rustbolt_base64            = { workspace = true }
rustbolt_collections       = { workspace = true }
rustbolt_core              = { workspace = true }
rustbolt_error             = { workspace = true }
rustbolt_hash              = { workspace = true }
rustbolt_hook              = { workspace = true }
rustbolt_plugin_javascript = { workspace = true }
rustbolt_util              = { workspace = true }
rustc-hash               = { workspace = true }
simd-json                = { workspace = true }
sugar_path               = { workspace = true }
tracing                  = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing"]
