[package]
description = "rustbolt module federation plugin"
edition     = "2021"
license     = "MIT"
name        = "rustbolt_plugin_mf"
repository  = "https://github.com/khulnasoft/rustbolt"
version     = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbolt_cacheable      = { workspace = true }
rustbolt_collections    = { workspace = true }
rustbolt_core           = { workspace = true }
rustbolt_error          = { workspace = true }
rustbolt_hash           = { workspace = true }
rustbolt_hook           = { workspace = true }
rustbolt_loader_runner  = { workspace = true }
rustbolt_plugin_runtime = { workspace = true }
rustbolt_util           = { workspace = true }

async-trait = { workspace = true }
hashlink    = { workspace = true }
itertools   = { workspace = true }
regex       = { workspace = true }
rustc-hash  = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true, features = ["rt"] }
tracing     = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["tracing", "rustbolt_hash"]
